baseURL = "https://againstthegiants.com"
languageCode = "en-us"
title = "Against The Giants"
theme = "papaya"

[markup.goldmark.renderer]
unsafe = true


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Chapters"
    pre = "pen-tool"
    url = "/chapters/"
    weight = 2
  [[menu.main]]
    name = "Links"
    pre = "link"
    url = "/links/"
    weight = 3
  